### ISSUE TITLE
1.16的下届合金工具没有计数进去

### ISSUE THREAD

**Issue by shenjackyuanjie** [Harveykang/FZ-sDataPack#4]
em
就像标题说的，你还没加下届合金工具的计数呢
你让我们这些快照服腐竹怎么活啊啊啊啊啊啊啊啊啊啊[doge]

**Comment by Harveykang** [comment]
[https://github.com/Harveykang/FZ-sDataPack/releases/tag/1.5-pre](url)
试试这个owo

**Comment by shenjackyuanjie** [comment]
哦 嘿嘿，谢谢啦嗯，我也会多抓虫，提高鲁棒性的！！
