### ISSUE TITLE
大佬，请问这个怎么用啊

### ISSUE THREAD

**Issue by 4O4NtFd** [Harveykang/FZ-sDataPack#5]

**Comment by shenjackyuanjie** [comment]
你需要先下载一个[发布版](https://github.com/Harveykang/FZ-sDataPack/releases)，然后把它解压，放到`world`文件夹下面的`datapack`文件夹，然后进游戏，重启服务器或者重进存档，或者输入指令`reload`，然后如果你看到了`数据包已经加载完成`的字样，就成了

**Comment by 4O4NtFd** [comment]
会了，谢谢大佬
