### ISSUE TITLE
[Server] java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Incorrect argument for command at position 48: ...arpet run <--[HERE]

### ISSUE THREAD

**Issue by ZhouYingde** [Harveykang/FZ-sDataPack#7]
[Server] [10:26:01] [main/INFO]: Loading for game Minecraft 1.15.2
[Server] [10:26:01] [main/WARN]: Mod `fabricproxy` (1.3.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[Server] [10:26:01] [main/WARN]: Mod ID bbor uses outdated schema version: 0 < 1
[Server] [10:26:01] [main/WARN]: Mod `autoconfig1` (1.2.0+mc1.14.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[Server] [10:26:01] [main/INFO]: [FabricLoader] Loading 41 mods: fabricproxy@1.3.0, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-renderer-api-v1@0.2.9+aea78a250c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.7.8+build.189, phosphor@0.5.2+build.6, bbor@1.0.14-1.15.1, fabric-renderer-indigo@0.2.22+203491ea0c, lithium@0.4.6, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-textures-v0@1.0.4+821cdba70c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, com_moandjiezana_toml_toml4j@0.7.2, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, autoconfig1@1.2.0+mc1.14.4, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.4.29+build.290-1.15, carpet@1.3.24, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, fabric-networking-v0@0.1.7+12515ed90c
[Server] [10:26:02] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/hairuo/MCDReforged-0.9.2-alpha/ditan/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[Server] [10:26:02] [main/INFO]: Lithium's configuration file was loaded successfully
[Server] [10:26:02] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.chunk.no_chunk_locking.MixinPalettedContainer' as no configuration enables it
[Server] [10:26:02] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinRedstoneWireBlock' as no configuration enables it
[Server] [10:26:02] [main/INFO]: Not applying mixin 'me.jellysquid.mods.lithium.mixin.redstone.MixinWorld' as no configuration enables it
[Server] [10:26:02] [main/INFO]: Transforming class net/minecraft/class_2382 using patch set 'Modify mutability flags in Vec3i'
[Server] [10:26:03] [main/INFO]: Transforming class net/minecraft/class_2338$class_2339 using patch set 'Use mutable fields in Vec3i'
[Server] [10:26:08] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[Server] [10:26:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[Server] [10:26:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[Server] [10:26:08] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[Server] [10:26:08] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[Server] [10:26:09] [main/INFO]: Definitely not up to no good
[Server] [10:26:09] [Server thread/INFO]: Starting minecraft server version 1.15.2
[Server] [10:26:09] [Server thread/INFO]: Loading properties
[Server] [10:26:09] [Server thread/INFO]: Default game type: SURVIVAL
[Server] [10:26:09] [Server thread/INFO]: Generating keypair
[Server] [10:26:09] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25757
[Server] [10:26:09] [Server thread/INFO]: Using epoll channel type
[Server] [10:26:10] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[Server] [10:26:10] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[Server] [10:26:10] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[Server] [10:26:10] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[Server] [10:26:10] [Server thread/INFO]: Preparing level "world"
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting tntDoNotUpdate as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting carpets as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting shulkerSpawningInEndCities as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting combineXPOrbs as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting onePlayerSleeping as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting spawnChunksSize as 11 from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting leadFix as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting xpNoCooldown as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting ctrlQCraftingFix as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting commandTick as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting fastRedstoneDust as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting commandDraw as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting commandPlayer as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting portalSuffocationFix as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting customMOTD as Hairuo Server 1.15.2 from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting commandScript as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting antiCheatDisabled as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting commandCameramode as false from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting missingTools as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting flippinCactus as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [CM]: loaded setting lagFreeSpawning as true from carpet.conf
[Server] [10:26:10] [Server thread/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[Server] [10:26:10] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit, FZ.sDatapack-1.4.4.zip, Fabric Mining Levels (v0), Hairuocrafting
[Server] [10:26:11] [Server thread/INFO]: Loaded 6 recipes
[Server] [10:26:11] [Server-Worker-3/ERROR]: Couldn't load function at fz:functions/carpet/scarpettagplayer.mcfunction
[Server] java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Incorrect argument for command at position 48: ...arpet run <--[HERE]
[Server] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
[Server] Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Incorrect argument for command at position 48: ...arpet run <--[HERE]
[Server] at net.minecraft.class_2158.method_9195(class_2158.java:61) ~[intermediary-server.jar:?]
[Server] at net.minecraft.class_2991.method_12909(class_2991.java:155) ~[intermediary-server.jar:?]
[Server] at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_252]
[Server] ... 6 more
[Server] [10:26:11] [Server-Worker-2/ERROR]: Couldn't load function at fz:functions/carpet/script.mcfunction
[Server] java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Incorrect argument for command at position 45: ...arpet run <--[HERE]
[Server] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) [?:1.8.0_252]
[Server] at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
[Server] at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
[Server] Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Incorrect argument for command at position 45: ...arpet run <--[HERE]
[Server] at net.minecraft.class_2158.method_9195(class_2158.java:61) ~[intermediary-server.jar:?]
[Server] at net.minecraft.class_2991.method_12909(class_2991.java:155) ~[intermediary-server.jar:?]
[Server] at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_252]
[Server] ... 6 more
[Server] [10:26:12] [Server thread/INFO]: Loaded 102 custom command functions
[Server] [10:26:12] [Server thread/INFO]: Loaded 825 advancements
[Server] [10:26:14] [Server thread/INFO]: create world dimension: 0 (seed: -3009433938551970963)
[Server] [10:26:14] [Server thread/INFO]: create world dimension: -1 (seed: -3009433938551970963)
[Server] [10:26:14] [Server thread/INFO]: create world dimension: 1 (seed: -3009433938551970963)
[Server] [10:26:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[Server] [10:26:15] [Server thread/INFO]: Preparing spawn area: 0%
[Server] [10:26:15] [Server thread/INFO]: Preparing spawn area: 0%
[Server] [10:26:15] [Server thread/INFO]: Preparing spawn area: 0%
[Server] [10:26:15] [Server thread/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:22] [Server-Worker-1/INFO]: Preparing spawn area: 0%
[Server] [10:26:23] [Server thread/INFO]: Preparing spawn area: 56%
[Server] [10:26:23] [Server thread/INFO]: Time elapsed: 9246 ms
[Server] [10:26:23] [Server thread/INFO]: Done (13.245s)! For help, type "help"

**Comment by ZhouYingde** [comment]
= UNDEFINED (22µs)]

**Comment by ZhouYingde** [comment]
Cause /script invoke to be unavailable

**Comment by Harveykang** [comment]
现在的2.0已经全面改为tagplayer啦~
